version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/smithy-docgen-core/src/main/resources/software/amazon/smithy/docgen/core/integrations/sphinx"
    schedule:
      interval: "weekly"
      day: "wednesday"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
